# Generated by Django 4.0.6 on 2022-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accept_email',
            field=models.IntegerField(choices=[(0, 'YES'), (1, 'NO')], default=1),
        ),
    ]
