# Generated by Django 4.0.2 on 2022-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accept_email',
            field=models.BooleanField(default=False),
        ),
    ]
