branch-defaults:
  main:
    environment: Backend-env
    group_suffix: null
environment-defaults:
  mysite-env:
    branch: null
    repository: null
global:
  application_name: backend
  branch: main
  default_ec2_keyname: my-keypair
  default_platform: Python 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
