branch-defaults:
  main:
    environment: backend-env
    group_suffix: null
environment-defaults:
  mysite-env:
    branch: null
    repository: null
global:
  application_name: backend
  branch: null
  default_ec2_keyname: my-keypair
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
