# Generated by Django 4.0.2 on 2023-06-29 23:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ava',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='modelLink',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.IntegerField(blank=True, choices=[(0, 'NLP'), (1, 'ML'), (2, 'SPEECH'), (3, 'CV'), (4, 'EMBED'), (5, 'OHTER'), (6, 'CAR'), (7, 'NET'), (8, 'STORY')], default=0),
        ),
        migrations.AddField(
            model_name='style',
            name='fontWeight',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='citation',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='index',
            name='style_id',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math'), (16, 'table'), (17, 'img_src')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math'), (16, 'table'), (17, 'img_src')], default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='cssId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='text',
            name='role',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math'), (16, 'table'), (17, 'img_src')], default=0),
        ),
    ]
