# Generated by Django 4.0.5 on 2022-06-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=200, unique=True)),
                ('link', models.CharField(max_length=200, unique=True)),
                ('fontSize', models.TextField()),
                ('indent', models.IntegerField()),
                ('decor', models.IntegerField(choices=[(0, 'Normal'), (1, 'Bold'), (2, 'Underline'), (3, 'Italic')], default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text', related_query_name='text', to='blog.post')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
