# Generated by Django 4.0.5 on 2022-08-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_view',
            new_name='total_visited',
        ),
    ]
