# Generated by Django 4.0.2 on 2022-10-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='text',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='text',
            name='type',
        ),
        migrations.AddField(
            model_name='appendix',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', related_query_name='next', to='blog.appendix'),
        ),
        migrations.AddField(
            model_name='citation',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.citation'),
        ),
        migrations.AddField(
            model_name='post',
            name='next_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='post',
            name='previous_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='blog.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='text',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.text'),
        ),
        migrations.AddField(
            model_name='text',
            name='role',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol')], default=0),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol')], default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='cssId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'Appendix'), (1, 'Text'), (2, 'Citation')], default=0)),
                ('kind_id', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('id_type', models.IntegerField(choices=[(0, 'Appendix'), (1, 'Text'), (2, 'Citation')], default=0)),
                ('style_id', models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='blog.post')),
            ],
        ),
    ]
