# Generated by Django 4.0.5 on 2022-06-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', related_query_name='text', to='blog.post'),
        ),
    ]
