# Generated by Django 4.0.2 on 2024-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currVer',
            field=models.FloatField(default=1.0),
        ),
    ]
