# Generated by Django 4.0.5 on 2022-08-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='blog.tag'),
        ),
    ]
