# Generated by Django 4.0.2 on 2022-08-26 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_text_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 26, 14, 18, 50, 314393)),
        ),
    ]
