# Generated by Django 4.0.2 on 2022-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_topic_alter_index_style_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='index',
            name='style_id',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.IntegerField(blank=True, choices=[(0, 'NLP'), (1, 'ML'), (2, 'SPEECH'), (3, 'CV'), (4, 'EMBED'), (5, 'OHTER'), (6, 'CAR'), (7, 'NET')], default=0),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html')], default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='role',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html')], default=0),
        ),
    ]
