# Generated by Django 4.0.5 on 2022-06-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_text_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['post']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.AlterField(
            model_name='text',
            name='fontSize',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation', related_query_name='citation', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendix', related_query_name='appendix', to='blog.post')),
            ],
        ),
    ]
