# Generated by Django 4.0.6 on 2022-08-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_user_alter_relationship_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eng_ver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.IntegerField(choices=[(0, 'VIE'), (1, 'ENG')], default=0),
        ),
    ]
