# Generated by Django 4.0.2 on 2022-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_citation_text_alter_index_style_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='fontWeight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='index',
            name='style_id',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.IntegerField(blank=True, choices=[(0, 'NLP'), (1, 'ML'), (2, 'SPEECH'), (3, 'CV'), (4, 'EMBED'), (5, 'OHTER'), (6, 'CAR'), (7, 'NET'), (8, 'STORY')], default=0),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math')], default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='role',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math')], default=0),
        ),
    ]
