# Generated by Django 4.0.2 on 2022-08-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_text_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='date_created',
        ),
        migrations.AddField(
            model_name='appendix',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.appendix'),
        ),
        migrations.AddField(
            model_name='citation',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.citation'),
        ),
        migrations.AddField(
            model_name='text',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.text'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'Appendix'), (1, 'Text'), (2, 'Citation')], default=0)),
                ('kind_id', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('id_type', models.IntegerField(choices=[(0, 'Appendix'), (1, 'Text'), (2, 'Citation')], default=0)),
                ('style_id', models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='blog.post')),
            ],
        ),
    ]
