# Generated by Django 4.0.5 on 2022-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_text_options_remove_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='indentLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appendix',
            name='text',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='text',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
