# Generated by Django 4.0.5 on 2022-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_appendix_indentlevel_appendix_text_citation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
