# Generated by Django 4.0.2 on 2022-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_style_fontweight_alter_index_style_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='fontWeight',
            field=models.IntegerField(default=100),
        ),
    ]
