# Generated by Django 4.0.2 on 2024-02-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('abstract', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['content'],
            },
        ),
    ]
