# Generated by Django 4.0.2 on 2022-10-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_eng_ver_post_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link')], default=0)),
                ('indentLevel', models.IntegerField(default=0)),
                ('fontSize', models.IntegerField(default=24)),
                ('decor', models.IntegerField(choices=[(0, 'Normal'), (1, 'Bold'), (2, 'Underline'), (3, 'Italic')], default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['content']},
        ),
        migrations.RemoveField(
            model_name='text',
            name='decor',
        ),
        migrations.RemoveField(
            model_name='text',
            name='fontSize',
        ),
        migrations.RemoveField(
            model_name='text',
            name='indent',
        ),
        migrations.RemoveField(
            model_name='text',
            name='title',
        ),
        migrations.AlterField(
            model_name='text',
            name='cssId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link')], default=0),
        ),
    ]
