# Generated by Django 4.0.2 on 2022-09-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_text_date_created_appendix_previous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendix',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', related_query_name='next', to='blog.appendix'),
        ),
    ]
