# Generated by Django 4.0.2 on 2022-09-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_appendix_previous'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='type',
            new_name='role',
        ),
    ]
