# Generated by Django 4.0.2 on 2024-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currVer',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
