# Generated by Django 4.0.5 on 2022-06-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_text_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['title']},
        ),
    ]
