# Generated by Django 4.0.2 on 2023-01-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_style_fontweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ava',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='index',
            name='style_id',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math'), (16, 'table')]),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math'), (16, 'table')], default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='role',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol'), (12, 'video'), (13, 'html'), (14, 'html_styled'), (15, 'math'), (16, 'table')], default=0),
        ),
    ]
