# Generated by Django 4.0.2 on 2024-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_currver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True)),
                ('day', models.CharField(blank=True, max_length=100)),
                ('content', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['content'],
            },
        ),
    ]
