# Generated by Django 4.0.5 on 2022-06-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_text_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
