# Generated by Django 4.0.2 on 2024-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
