# Generated by Django 4.0.2 on 2022-09-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_style_options_post_pdf_post_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='next_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='previous_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='blog.post'),
        ),
    ]
