# Generated by Django 4.0.2 on 2024-09-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_update_options_update_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ver',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
