# Generated by Django 4.0.2 on 2022-10-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_next_post_post_previous_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='cssId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
