# Generated by Django 4.0.2 on 2024-11-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
