# Generated by Django 4.0.2 on 2022-10-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_text_cssid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='style_id',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol')]),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol')], default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='role',
            field=models.IntegerField(choices=[(0, 'paragraph'), (1, 'image'), (2, 'header'), (3, 'link'), (4, 'citation'), (5, 'appendix'), (6, 'h1'), (7, 'h2'), (8, 'h3'), (9, 'h4'), (10, 'code'), (11, 'ol')], default=0),
        ),
    ]
